#!/usr/bin/perl
################################################################################
# Euler 2
# Even Fibonacci numbers
# Author: Eugene Kolo - 2014
# Contact: www.eugenekolo.com

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
################################################################################

use strict;
use Eulerlib;

my $fib = 0;
my $sum = 0;
my $term = 1;
while ($fib < 4_000_000) {
    if ($fib % 2 == 0) {
        $sum += $fib;
    }
    $term += 1;
    $fib = Eulerlib::fib($term);
}
print "$sum\n";
